on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Installs and configure Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          dockerd &
          sleep 5
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Extract version from package.json
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Build docker image
        run: docker build -t onecomputerguy/peppr:v${{ steps.package_version.outputs.version }} -t onecomputerguy/peppr:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Push docker image (version specific and latest)
        run: docker push onecomputerguy/peppr:v${{ steps.package_version.outputs.version }} && docker push onecomputerguy/peppr:latest
